//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by hand to provide a strongly-typed accessor for
//     Strings.resx / Strings.<culture>.resx via ResourceManager.
//
//     The accessor uses {x:Static p:Strings.X} in XAML, which evaluates at
//     parse time. UI strings refresh on culture change after app restart.
//
//     Cultura é controlada em App.xaml.cs via
//     Thread.CurrentThread.CurrentUICulture antes da janela principal carregar.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable
using System.Globalization;
using System.Resources;

namespace OptiRoute.App.Properties;

/// <summary>
/// Strongly-typed accessor para <c>Strings.resx</c> (en-US fallback) e
/// <c>Strings.&lt;culture&gt;.resx</c> (satélites, ex.: pt-BR).
/// Cultura é lida de <see cref="CultureInfo.CurrentUICulture"/> — definida
/// em <c>App.xaml.cs.OnStartup</c> a partir de config ou system culture.
/// </summary>
internal static class Strings
{
    private static ResourceManager _resourceManager;

    /// <summary>ResourceManager compartilhado (singleton, thread-safe).</summary>
    public static ResourceManager ResourceManager
    {
        get
        {
            if (_resourceManager is null)
            {
                _resourceManager = new ResourceManager(
                    "OptiRoute.App.Strings",
                    typeof(Strings).Assembly);
            }
            return _resourceManager;
        }
    }

    /// <summary>
    /// Cultura atual (configurável em App.xaml.cs).
    /// Default: <see cref="CultureInfo.CurrentUICulture"/>.
    /// </summary>
    public static CultureInfo Culture
    {
        get => CultureInfo.CurrentUICulture;
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private static string Get(string name)
        => ResourceManager.GetString(name, Culture) ?? $"[{name}]";

    // ── MainWindow.xaml ────────────────────────────────────────────────────

    public static string MainWindow_Title              => Get("MainWindow.Title");
    public static string MainWindow_BrandName           => Get("MainWindow.BrandName");
    public static string MainWindow_ArchitectureBadge  => Get("MainWindow.ArchitectureBadge");
    public static string MainWindow_OpnsenseLabel      => Get("MainWindow.OpnsenseLabel");
    public static string MainWindow_ThisComputerLabel  => Get("MainWindow.ThisComputerLabel");
    public static string MainWindow_RefreshButton      => Get("MainWindow.RefreshButton");
    public static string MainWindow_ApplyRepairButton   => Get("MainWindow.ApplyRepairButton");
    public static string MainWindow_RefreshButtonToolTip  => Get("MainWindow.RefreshButton.ToolTip");
    public static string MainWindow_ApplyRepairButtonToolTip => Get("MainWindow.ApplyRepairButton.ToolTip");
    public static string MainWindow_AddApplicationButton => Get("MainWindow.AddApplicationButton");
    public static string MainWindow_NotConnectedState_Action => Get("MainWindow.NotConnectedState.Action");
    public static string MainWindow_SettingsButtonToolTip => Get("MainWindow.SettingsButtonToolTip");
    public static string MainWindow_GatewaysLabel      => Get("MainWindow.GatewaysLabel");
    public static string MainWindow_EmptyState_Title   => Get("MainWindow.EmptyState.Title");
    public static string MainWindow_EmptyState_Subtitle => Get("MainWindow.EmptyState.Subtitle");
    public static string MainWindow_EmptyState_AddButton => Get("MainWindow.EmptyState.AddButton");
    public static string MainWindow_Button_AddFirstApp => Get("MainWindow.Button.AddFirstApp");
    public static string MainWindow_VersionFooter      => Get("MainWindow.VersionFooter");
    public static string MainWindow_SettingsPanel_Title => Get("MainWindow.SettingsPanel.Title");
    public static string MainWindow_SettingsPanel_FirstRunHint => Get("MainWindow.SettingsPanel.FirstRunHint");

    // ── MainWindow — Status bar / loading stages (Phase 2 UX) ──────────────

    public static string MainWindow_StatusBar_Connected    => Get("MainWindow.StatusBar.Connected");
    public static string MainWindow_StatusBar_Disconnected => Get("MainWindow.StatusBar.Disconnected");
    public static string MainWindow_StatusBar_Connecting   => Get("MainWindow.StatusBar.Connecting");
    public static string MainWindow_StatusBar_Cancel       => Get("MainWindow.StatusBar.Cancel");
    public static string MainWindow_StatusBar_TlsHint      => Get("MainWindow.StatusBar.TlsHint");
    public static string MainWindow_LoadingStage_ReadingRules    => Get("MainWindow.LoadingStage.ReadingRules");
    public static string MainWindow_LoadingStage_ComparingQos    => Get("MainWindow.LoadingStage.ComparingQos");
    public static string MainWindow_LoadingStage_BuildingPlan    => Get("MainWindow.LoadingStage.BuildingPlan");
    public static string MainWindow_LoadingStage_ApplyingChanges => Get("MainWindow.LoadingStage.ApplyingChanges");

    // ── Card — Synchronized state ──────────────────────────────────────────

    public static string Card_GlobalDefaultLabel       => Get("Card.GlobalDefaultLabel");
    public static string Card_DefaultRoutingLabel      => Get("Card.DefaultRoutingLabel");
    public static string Card_ThisComputerCardLabel    => Get("Card.ThisComputerCardLabel");
    public static string Card_FollowGlobalRadio        => Get("Card.FollowGlobalRadio");
    public static string Card_LocalOverrideRadio       => Get("Card.LocalOverrideRadio");
    public static string Card_OverrideDescription      => Get("Card.OverrideDescription");
    public static string Card_EffectiveRouteLabel      => Get("Card.EffectiveRouteLabel");
    public static string Card_Route_GlobalLabel        => Get("Card.Route.GlobalLabel");
    public static string Card_Route_ThisPcLabel        => Get("Card.Route.ThisPcLabel");
    public static string Card_Route_EffectiveLabel     => Get("Card.Route.EffectiveLabel");
    public static string Card_Route_UseGlobal          => Get("Card.Route.UseGlobal");
    public static string Card_Route_EmptyValue         => Get("Card.Route.EmptyValue");
    public static string Card_Route_ChangeButton       => Get("Card.Route.ChangeButton");

    // ── Card — LocalOnly state ─────────────────────────────────────────────

    public static string Card_LocalOnly_Title          => Get("Card.LocalOnly.Title");
    public static string Card_LocalOnly_Subtitle       => Get("Card.LocalOnly.Subtitle");
    public static string Card_LocalOnly_RegisterButton => Get("Card.LocalOnly.RegisterButton");
    public static string Card_LocalOnly_RemoveButton   => Get("Card.LocalOnly.RemoveButton");

    // ── Card — GlobalOnly state ────────────────────────────────────────────

    public static string Card_GlobalOnly_Title         => Get("Card.GlobalOnly.Title");
    public static string Card_GlobalOnly_Subtitle      => Get("Card.GlobalOnly.Subtitle");
    public static string Card_GlobalOnly_Hint           => Get("Card.GlobalOnly.Hint");
    public static string Card_GlobalOnly_ActivateButton => Get("Card.GlobalOnly.ActivateButton");

    // ── Card — Out-of-sync (conflict) state ────────────────────────────────

    public static string Card_Conflict_Title           => Get("Card.Conflict.Title");
    public static string Card_Conflict_Subtitle        => Get("Card.Conflict.Subtitle");
    public static string Card_Conflict_Hint             => Get("Card.Conflict.Hint");
    public static string Card_Conflict_RepairButton   => Get("Card.Conflict.RepairButton");

    // ── Card — common ──────────────────────────────────────────────────────

    public static string Card_DeleteButton_ToolTip     => Get("Card.DeleteButton.ToolTip");
    public static string Card_DscpBadge_Format(int dscp) => string.Format(Culture, Get("Card.DscpBadge"), dscp);

    // ── Dialog.InvalidTos ──────────────────────────────────────────────────

    public static string Dialog_InvalidTos_Title              => Get("Dialog.InvalidTos.Title");
    public static string Dialog_InvalidTos_DescriptionLabel  => Get("Dialog.InvalidTos.DescriptionLabel");
    public static string Dialog_InvalidTos_ActualTosLabel     => Get("Dialog.InvalidTos.ActualTosLabel");
    public static string Dialog_InvalidTos_CancelButton       => Get("Dialog.InvalidTos.CancelButton");
    public static string Dialog_InvalidTos_ForceWindowsButton => Get("Dialog.InvalidTos.ForceWindowsButton");
    public static string Dialog_InvalidTos_ForceOpnsenseButton => Get("Dialog.InvalidTos.ForceOpnsenseButton");

    // ── Dialog.AdminElevation ──────────────────────────────────────────────

    public static string Dialog_AdminElevation_Title          => Get("Dialog.AdminElevation.Title");
    public static string Dialog_AdminElevation_Message        => Get("Dialog.AdminElevation.Message");
    public static string Dialog_AdminElevation_RestartButton  => Get("Dialog.AdminElevation.RestartButton");
    public static string Dialog_AdminElevation_ContinueButton => Get("Dialog.AdminElevation.ContinueButton");

    // ── Dialog.Reset ───────────────────────────────────────────────────────

    public static string Dialog_Reset_Title        => Get("Dialog.Reset.Title");
    public static string Dialog_Reset_Message      => Get("Dialog.Reset.Message");
    public static string Dialog_Reset_CancelButton => Get("Dialog.Reset.CancelButton");
    public static string Dialog_Reset_ResetButton  => Get("Dialog.Reset.ResetButton");
    public static string Dialog_Reset_Failed(string detail)
        => string.Format(Culture, Get("Dialog.Reset.Failed"), detail);

    // ── Common ─────────────────────────────────────────────────────────────

    public static string Common_Cancel   => Get("Common.Cancel");
    public static string Common_Save     => Get("Common.Save");
    public static string Common_Close    => Get("Common.Close");
    public static string Common_Loading  => Get("Common.Loading");

    // ── Settings window ───────────────────────────────────────────────────

    public static string Settings_WindowTitle               => Get("Settings.WindowTitle");
    public static string Settings_Tab_Connection           => Get("Settings.Tab.Connection");
    public static string Settings_Tab_Credentials          => Get("Settings.Tab.Credentials");
    public static string Settings_Tab_Gateways              => Get("Settings.Tab.Gateways");
    public static string Settings_Tab_Advanced              => Get("Settings.Tab.Advanced");

    public static string Settings_Connection_OpnsenseAddress => Get("Settings.Connection.OpnsenseAddress");
    public static string Settings_Connection_LocalComputer  => Get("Settings.Connection.LocalComputer");
    public static string Settings_Connection_DetectIpButton  => Get("Settings.Connection.DetectIpButton");
    public static string Settings_Connection_PreferredIp    => Get("Settings.Connection.PreferredIp");
    public static string Settings_Connection_TestButton     => Get("Settings.Connection.TestButton");
    public static string Settings_Connection_TestRunning    => Get("Settings.Connection.TestRunning");
    public static string Settings_Connection_TestFailedAuth => Get("Settings.Connection.TestFailedAuth");
    public static string Settings_Connection_TestFailedNetwork => Get("Settings.Connection.TestFailedNetwork");
    public static string Settings_Connection_TestSuccess(string version, string latency)
        => string.Format(Culture, Get("Settings.Connection.TestSuccess"), version, latency);
    public static string Settings_Connection_AllowInsecureTls        => Get("Settings.Connection.AllowInsecureTls");
    public static string Settings_Connection_InsecureTlsWarning      => Get("Settings.Connection.InsecureTlsWarning");
    public static string Settings_Connection_TlsErrorHint            => Get("Settings.Connection.TlsErrorHint");
    public static string Settings_Connection_TlsErrorHint_Short      => Get("Settings.Connection.TlsErrorHint.Short");
    public static string Settings_Connection_AllowInsecureTlsTooltip => Get("Settings.Connection.AllowInsecureTlsTooltip");
    public static string Settings_Connection_OpnsenseVersionLabel    => Get("Settings.Connection.OpnsenseVersionLabel");
    public static string Settings_Connection_OpnsenseVersionUnknown  => Get("Settings.Connection.OpnsenseVersionUnknown");

    public static string Settings_Credentials_ApiKey       => Get("Settings.Credentials.ApiKey");
    public static string Settings_Credentials_ApiSecret    => Get("Settings.Credentials.ApiSecret");
    public static string Settings_Credentials_RevealSecret => Get("Settings.Credentials.RevealSecret");
    public static string Settings_Credentials_HideSecret   => Get("Settings.Credentials.HideSecret");
    public static string Settings_Credentials_ImportFile   => Get("Settings.Credentials.ImportFile");
    public static string Settings_Credentials_ImportSuccess => Get("Settings.Credentials.ImportSuccess");
    public static string Settings_Credentials_ImportFailed => Get("Settings.Credentials.ImportFailed");
    public static string Settings_Credentials_HowToCreate  => Get("Settings.Credentials.HowToCreate");

    public static string Settings_Gateways_ColumnDisplayName  => Get("Settings.Gateways.ColumnDisplayName");
    public static string Settings_Gateways_ColumnOpnsenseName => Get("Settings.Gateways.ColumnOpnsenseName");
    public static string Settings_Gateways_ColumnStatus       => Get("Settings.Gateways.ColumnStatus");
    public static string Settings_Gateways_ColumnActions      => Get("Settings.Gateways.ColumnActions");
    public static string Settings_Gateways_ResetButton        => Get("Settings.Gateways.ResetButton");
    public static string Settings_Gateways_WaitingForCredentials => Get("Settings.Gateways.WaitingForCredentials");
    public static string MainWindow_ToolTip_LanguageSelector => Get("MainWindow.ToolTip.LanguageSelector");
    public static string Card_SyncStateBadge_Synchronized => Get("Card.SyncStateBadge.Synchronized");
    public static string Card_SyncStateBadge_LocalOnly    => Get("Card.SyncStateBadge.LocalOnly");
    public static string Card_SyncStateBadge_GlobalOnly   => Get("Card.SyncStateBadge.GlobalOnly");
    public static string Card_SyncStateBadge_Conflict     => Get("Card.SyncStateBadge.Conflict");
    public static string Card_SyncStateBadge_Unknown      => Get("Card.SyncStateBadge.Unknown");
    public static string Settings_Gateways_ResetButtonToolTip => Get("Settings.Gateways.ResetButtonToolTip");
    public static string Settings_Gateways_EditDisplayNameToolTip => Get("Settings.Gateways.EditDisplayNameToolTip");
    public static string Settings_Gateways_Loading            => Get("Settings.Gateways.Loading");
    public static string Settings_Gateways_NoneFound          => Get("Settings.Gateways.NoneFound");
    public static string Settings_Gateways_SaveCredentialsFirst => Get("Settings.Gateways.SaveCredentialsFirst");

    // Validation messages (Phase 1.3)
    public static string Settings_Validation_HostRequired       => Get("Settings.Validation.HostRequired");
    public static string Settings_Validation_HostInvalid        => Get("Settings.Validation.HostInvalid");
    public static string Settings_Validation_PreferredIpInvalid => Get("Settings.Validation.PreferredIpInvalid");
    public static string Settings_Validation_ApiKeyRequired     => Get("Settings.Validation.ApiKeyRequired");
    public static string Settings_Validation_ApiKeyTooShort     => Get("Settings.Validation.ApiKeyTooShort");
    public static string Settings_Validation_ApiSecretRequired  => Get("Settings.Validation.ApiSecretRequired");
    public static string Settings_Validation_ApiSecretTooShort  => Get("Settings.Validation.ApiSecretTooShort");
    public static string Settings_Validation_DscpRangeInvalid   => Get("Settings.Validation.DscpRangeInvalid");
    public static string Settings_Validation_LogRetentionInvalid => Get("Settings.Validation.LogRetentionInvalid");
    public static string Settings_Connection_AutoTestStatus_Idle     => Get("Settings.Connection.AutoTestStatus.Idle");
    public static string Settings_Connection_AutoTestStatus_Checking => Get("Settings.Connection.AutoTestStatus.Checking");
    public static string Settings_Connection_AutoTestStatus_Success  => Get("Settings.Connection.AutoTestStatus.Success");
    public static string Settings_Connection_AutoTestStatus_Failed   => Get("Settings.Connection.AutoTestStatus.Failed");
    public static string Settings_Connection_AllowSelfSignedButton       => Get("Settings.Connection.AllowSelfSignedButton");
    public static string Settings_Connection_AutoTest_Error_Authentication => Get("Settings.Connection.AutoTest.Error.Authentication");
    public static string Settings_Connection_AutoTest_Error_Timeout      => Get("Settings.Connection.AutoTest.Error.Timeout");
    public static string Settings_Connection_AutoTest_Error_Tls          => Get("Settings.Connection.AutoTest.Error.Tls");

    public static string Settings_Advanced_StartWithWindows => Get("Settings.Advanced.StartWithWindows");
    public static string Settings_Advanced_MinimizeToTray   => Get("Settings.Advanced.MinimizeToTray");
    public static string Settings_Advanced_ShowTechnical    => Get("Settings.Advanced.ShowTechnical");
    public static string Settings_Advanced_LogRetention     => Get("Settings.Advanced.LogRetention");
    public static string Settings_Advanced_DscpPoolToggle   => Get("Settings.Advanced.DscpPoolToggle");
    public static string Settings_Advanced_DscpPoolStart    => Get("Settings.Advanced.DscpPoolStart");
    public static string Settings_Advanced_DscpPoolEnd      => Get("Settings.Advanced.DscpPoolEnd");
    public static string Settings_Advanced_ResetToDefaultsDescription => Get("Settings.Advanced.ResetToDefaultsDescription");
    public static string Settings_Advanced_ResetToDefaultsButton      => Get("Settings.Advanced.ResetToDefaultsButton");

    public static string Wizard_Welcome_Title    => Get("Wizard.Welcome.Title");
    public static string Wizard_Welcome_Subtitle => Get("Wizard.Welcome.Subtitle");
    public static string Wizard_Step_Connection  => Get("Wizard.Step.Connection");
    public static string Wizard_Step_Credentials => Get("Wizard.Step.Credentials");
    public static string Wizard_Step_Computer    => Get("Wizard.Step.Computer");
    public static string Wizard_Step_Gateways    => Get("Wizard.Step.Gateways");
    public static string Wizard_Step_Validation  => Get("Wizard.Step.Validation");
    public static string Wizard_Step_Finish      => Get("Wizard.Step.Finish");
    public static string Wizard_BackButton       => Get("Wizard.BackButton");
    public static string Wizard_NextButton       => Get("Wizard.NextButton");
    public static string Wizard_FinishButton     => Get("Wizard.FinishButton");
    public static string Wizard_LaunchButton     => Get("Wizard.LaunchButton");
    public static string Wizard_ValidationChecking => Get("Wizard.ValidationChecking");
    public static string Wizard_ValidationPassed => Get("Wizard.ValidationPassed");
    public static string Wizard_CheckConnectionOk => Get("Wizard.CheckConnectionOk");
    public static string Wizard_CheckCredentialsOk => Get("Wizard.CheckCredentialsOk");
    public static string Wizard_CheckIpOk         => Get("Wizard.CheckIpOk");
    public static string Wizard_CheckGatewayOk    => Get("Wizard.CheckGatewayOk");
    public static string Wizard_CheckPersistOk    => Get("Wizard.CheckPersistOk");

    // ── Status messages ────────────────────────────────────────────────────

    public static string Status_Refreshing              => Get("Status.Refreshing");
    public static string Status_NothingToRepair         => Get("Status.NothingToRepair");
    public static string Status_Applying(int count)    => string.Format(Culture, Get("Status.Applying"), count);
    public static string Status_ApplySuccess(int count) => string.Format(Culture, Get("Status.ApplySuccess"), count);
    public static string Status_ApplyPartialFailure(int applied, int failed)
        => string.Format(Culture, Get("Status.ApplyPartialFailure"), applied, failed);
    public static string Status_ApplyFailed(string detail) => string.Format(Culture, Get("Status.ApplyFailed"), detail);
    public static string Status_ApplyRepair_Cancelled    => Get("Status.ApplyRepair.Cancelled");
    public static string Status_RefreshSuccess(int count) => string.Format(Culture, Get("Status.RefreshSuccess"), count);
    public static string Status_RefreshFailed(string detail) => string.Format(Culture, Get("Status.RefreshFailed"), detail);
    public static string Status_RemoveFailed            => Get("Status.RemoveFailed");
    public static string Status_Connecting              => Get("Status.Connecting");
    public static string Status_ConnectionFailed        => Get("Status.ConnectionFailed");
    public static string Status_Registering(string exeName) => string.Format(Culture, Get("Status.Registering"), exeName);
    public static string Status_RegisterSuccess(string exeName) => string.Format(Culture, Get("Status.RegisterSuccess"), exeName);
    public static string Status_AlreadyRegistered(string exeName) => string.Format(Culture, Get("Status.AlreadyRegistered"), exeName);
    public static string Status_GenericError(string detail) => string.Format(Culture, Get("Status.GenericError"), detail);
    public static string Status_OpenLogFolderFailed => Get("Status.OpenLogFolderFailed");

    // ── Phase 3 — Diagnostics export / About / Tray ────────────────────────

    public static string MainWindow_Button_ExportDiagnostics => Get("MainWindow.Button.ExportDiagnostics");
    public static string MainWindow_OpenLogFolderButton       => Get("MainWindow.OpenLogFolderButton");
    public static string MainWindow_OpenLogFolderTooltip      => Get("MainWindow.OpenLogFolderTooltip");
    public static string DiagnosticsExport_Success(string path) => string.Format(Culture, Get("DiagnosticsExport.Success"), path);
    public static string DiagnosticsExport_Failed(string detail) => string.Format(Culture, Get("DiagnosticsExport.Failed"), detail);

    public static string About_Title       => Get("About.Title");
    public static string About_Version(string version) => string.Format(Culture, Get("About.Version"), version);
    public static string About_Description => Get("About.Description");
    public static string About_License     => Get("About.License");
    public static string About_Repository  => Get("About.Repository");
    public static string About_Issues      => Get("About.Issues");
    public static string About_Copyright(string holder) => string.Format(Culture, Get("About.Copyright"), holder);
    public static string About_OkButton    => Get("About.OkButton");

    public static string Tray_Menu_Show => Get("Tray.Menu.Show");
    public static string Tray_Menu_Quit => Get("Tray.Menu.Quit");
    public static string Tray_Menu_Resync => Get("Tray.Menu.Resync");

    // ── ApplyFailuresDialog.xaml ───────────────────────────────────────────

    public static string Card_ApplyFailures_Title              => Get("Card.ApplyFailures.Title");
    public static string Card_ApplyFailures_Subtitle(int verifiedCount, int failedCount)
        => string.Format(Culture, Get("Card.ApplyFailures.Subtitle"), verifiedCount, failedCount);
    public static string Card_ApplyFailures_ItemHeader(string executable, string actionType)
        => string.Format(Culture, Get("Card.ApplyFailures.ItemHeader"), executable, actionType);
    public static string Card_ApplyFailures_CopyDetailsButton  => Get("Card.ApplyFailures.CopyDetailsButton");
    public static string Card_ApplyFailures_OpenLogButton      => Get("Card.ApplyFailures.OpenLogButton");
    public static string Card_ApplyFailures_CloseButton        => Get("Card.ApplyFailures.CloseButton");
    public static string Card_ApplyFailures_EmptyState         => Get("Card.ApplyFailures.EmptyState");

    // ── Add Application dialog (file picker + running process scanner) ─────

    public static string AddApplication_Title              => Get("AddApplication.Title");
    public static string AddApplication_ExecutableLabel    => Get("AddApplication.ExecutableLabel");
    public static string AddApplication_DisplayNameLabel   => Get("AddApplication.DisplayNameLabel");
    public static string AddApplication_BrowseButton       => Get("AddApplication.BrowseButton");
    public static string AddApplication_RunningApps        => Get("AddApplication.RunningApps");
    public static string AddApplication_NoRunningApps      => Get("AddApplication.NoRunningApps");
    public static string AddApplication_RefreshButton      => Get("AddApplication.RefreshButton");
    public static string AddApplication_OkButton           => Get("AddApplication.OkButton");
    public static string AddApplication_CancelButton       => Get("AddApplication.CancelButton");
    public static string AddApplication_ExecutableRequired => Get("AddApplication.ExecutableRequired");
    public static string AddApplication_GatewayLabel       => Get("AddApplication.GatewayLabel");
    public static string AddApplication_Subtitle           => Get("AddApplication.Subtitle");
    public static string AddApplication_NoRunningAppsHint  => Get("AddApplication.NoRunningAppsHint");

    // ── Banner — avisos não bloqueantes (G16: IP local dinâmico) ───────────

    public static string Banner_IpChange_Title => Get("Banner.IpChange.Title");
    public static string Banner_IpChange_Message(string configured, string current)
        => string.Format(Culture, Get("Banner.IpChange.Message"), configured, current);
    public static string Banner_DismissTooltip => Get("Banner.DismissTooltip");
}
